### ISSUE TITLE
issue with .virlrc file

### ISSUE THREAD

**Issue by dvcraig88** [CiscoDevNet/sd-wan-ansible-pipeline-code#2]
When running the build.yml file I am unable to read the .virlrc file correctly to obtain the variable.  Is there a specific location to place this file?  Currently created in the same folder as the build.yml, also tried placing in the inventory folder.  Current work around is to configure virl server, username and password in build.yml.

**Comment by jasonking3** [comment]
If you use this repo with the Multi-IOS sandbox on DevNet, you don't actually need a .virlrc because it is already there on the DevBox.  But if you using it against your own VIRL server, you will need the .virlrc.  It should just be put in the base directory for the repo and needs to specify values for the following variables:

VIRL_USERNAME=guest
VIRL_PASSWORD=guest
VIRL_HOST=your.virl.server

**Comment by dvcraig88** [comment]
I was able to overcome this by actually using the export commands so the build.yml would pick up the variables.

export VIRL_HOST=10.10.20.160
export VIRL_USERNAME=guest
export VIRL_PASSWORD=guest
