### ISSUE TITLE
issue running configure.yml - install serial file

### ISSUE THREAD

**Issue by dvcraig88** [CiscoDevNet/sd-wan-ansible-pipeline-code#3]
It was explained that we needed a license file to run the configure.yml, however it's asking for the serial file.  Is this the .viptela file retrieved from plug and play?  I am able to manually build out the vedges by creating a root certificate on vmanage and then creating certs for all of the devices.  It appears the configure.yml is automating this process but for me the problem is I need to install the cert before I can retrieve a serial number.

**Comment by jasonking3** [comment]
This repo actually has a serialFile.viptela file in the licenses directory.  It is for demo purposes only and allows a small number of vedges.  Otherwise, if you want to build a larger topology, you can use the software.cisco.com portal to create and download a larger serial file and put that in the licenses directory.  This repo should work as-is, though, when it comes to the org name and serial file for the topology shown in the README.  Is it not?

**Comment by dvcraig88** [comment]
I see that the serialfile.viptela is in that folder however after running the build.yml I am not attempting to run configure.yml and see the following error.

![configure-error](https://user-images.githubusercontent.com/52972768/61320525-2ad23980-a7cf-11e9-8da5-900c28d60160.JPG)

**Comment by jasonking3** [comment]
Did you use the --recursive switch when you did the git clone?  That looks like it might be missing the the ansible-viptela submodule in the roles directory.

**Comment by dvcraig88** [comment]
You are correct I was missing the roles directory.  Also needed to put the virl export commands as well.
